name: app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  audioplayers: ^6.5.1
  confetti: ^0.8.0
  flutter_launcher_icons: ^0.14.4
  url_launcher: ^6.3.2
  shared_preferences: ^2.5.3
  image_picker: ^1.2.1
  path_provider: ^2.1.5
  flutter_image_compress: ^2.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter_icons:
  android: true
  image_path: "assets/icon/amor.png"

flutter:
  uses-material-design: true
  
  assets:
    - lib/assets/snoopy.gif
    - lib/assets/pop.wav
    - lib/assets/images/